DROP TABLE IF EXISTS proizvod cascade;

create table proizvod (id bigint generated by default as identity, cena float(53) not null, image_url varchar(255), naziv varchar(255), opis varchar(255), primary key (id));

insert into proizvod (id, cena, image_url, naziv, opis) values (default, 199.99, 'https://www.metropolitan.ac.rs/files/2018/11/logo-01-1.png', 'Neki naziv', 'Opis krad fajnds fja n');
insert into proizvod (id, cena, image_url, naziv, opis) values (default, 349.99, 'https://www.metropolitan.ac.rs/files/2018/11/logo-01-1.png', 'Neki naziv 2', 'Ovo je najbolji proizv');
insert into proizvod (id, cena, image_url, naziv, opis) values (default, 29.99, 'https://www.metropolitan.ac.rs/files/2018/11/logo-01-1.png', 'Neki naziv 3', 'hfajds hfui ahdif');
